### ISSUE TITLE
Request for dataset processing code

### ISSUE THREAD

**Issue by Chohoonhee** [Huawei-BIC/Discrete_Time_Convolution_for_Fast_Event_Based_Stereo#1]
I would like to express my gratitude for your hard work and for making your code available to the public. I am writing to ask for some assistance regarding the use of your code for training a network. There seem to be a few issues, particularly with the DSEC dataset, which is provided in the h5 format. It appears that you have preprocessed the data into npy format. Would it be possible for you to share the preprocessing code for this as well? The same request applies to the MVSEC dataset. Once again, thank you very much.

**Comment by CheKaiWei** [comment]
We add the data preprocess method in the code.

Data preprocess for DSEC: \
Follow from https://github.com/uzh-rpg/DSEC.

Data process for MVSEC (SBT): \
Step 1: From h5 file to npy file: follow from https://github.com/tlkvstepan/event_stereo_ICCV2019. \
Step 2: Using SBT method to proccess npy file: `python code_of_mvsec/data_preprocess.py`

**Comment by AllenZyy821** [comment]
Thank u for ur sharing! but I find that in event-stereo-ICCV2019, convert raw MVSEC to rectified dataset takes a really long time, I wonder does it normal? I ran the convert_mvsec.py code nearly one day but only converted about 60 pairs data...
