### ISSUE TITLE
datasets for train

### ISSUE THREAD

**Issue by cvwwei** [Huawei-BIC/Discrete_Time_Convolution_for_Fast_Event_Based_Stereo#2]
The code will only work if there is an SBT stack representation rather than raw data. Could you please share it?

**Comment by CheKaiWei** [comment]
Here is our SBT method:

Data process for MVSEC (SBT): \
Step 1: From h5 file to npy file: follow from https://github.com/tlkvstepan/event_stereo_ICCV2019. \
Step 2: Using SBT method to proccess npy file: `python code_of_mvsec/data_preprocess.py`
